package Apr13;

public class ExceptionTest {

    public static void main(String[] args) {
        //try catch
        // 프로그램 실행시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
        int num = 100;
        int result = 0;

        for(int i=0; i < 10; i++) {
            try {
                result = num / (int) (Math.random() * 10);
                System.out.println(result);
            }catch (ArithmeticException e) {
                System.out.println("0");
            }
        }
        // 0을나눌수 없어 에러가 뜨면 catch문이 출력된다.
        // **에러가 뜨면 try문을 벗어난다**

        //예외 발생시키기
        Exception exception = new Exception("고의로 에러발생");

        try {
            throw exception;
        }catch (Exception e) {
            System.out.println(exception.getMessage());
            System.out.println("에러발생");
        } finally {
            System.out.println("fianlly : 예외의 여부산관없이 실행시키는 코드");
            System.out.println("try->(에러발생시)catch->finally 순");
        }

    }

}
